### ISSUE TITLE
Could you please help me with setting up vpnfailsafe in openSUSE leap 42.2 ?

### ISSUE THREAD

**Issue by woyaojizhu8** [wknapik/vpnfailsafe#11]
I'm using NetworkManager's GUI to set my openvpn connection, and I have found nothing in /etc/openvpn. How to find my "<your_provider>.conf" , and where should I put vpnfailsafe.sh to ?

**Comment by wknapik** [comment]
Hi @woyaojizhu8. 

I don't use NetworkManager myself, but I hear `vpnfailsafe` can be used pretty much the same way when the VPN connection is handled by NetworkManager.

I assume NetworkManager is fed an OpenVPN config one way, or another. Perhaps it's not stored in /etc/openvpn (or /etc/openvpn/client), but that's not really relevant. You can just save vpnfailsafe.sh anywhere (/etc/openvpn would be fine), make it executable, and then modify the config file you use to configure your VPN connection in NetworkManager, according to the [README](https://github.com/wknapik/vpnfailsafe/blob/master/README.md) file.

If your VPN connection is not configured yet, you should consult the documentation provided by your VPN provider. It will include a download link for the config file (referred to as "<your_provider.conf" in the README), as well as further instructions.

If you haven't chosen a VPN provider yet, here's a list you could use to pick one - https://torrentfreak.com/vpn-services-anonymous-review-2017-170304/

Let me know how it goes.

PS. The Arch wiki is a good source of info about configuring [OpenVPN](https://wiki.archlinux.org/index.php/Openvpn) and [NetworkManager](https://wiki.archlinux.org/index.php/NetworkManager), regardless of which distro you're using.

**Comment by wknapik** [comment]
Correction: seems NetworkManager doesn't support the OpenVPN --up/--down options. It has it's own mechanism.

https://www.google.com/search?q=networkmanager+openvpn+up+script - the first links describe how to use it.

Or you could just use OpenVPN via systemd - https://wiki.archlinux.org/index.php/OpenVPN#Letting_NetworkManager_start_a_connection - and get the full functionality, including --up/--down. In this case, the regular `vpnfailsafe` README applies.

Sorry for the misleading initial answer. I'll close this issue - it's been 2 weeks since the last response, but feel free to open a new one if you still need help.
