### ISSUE TITLE
Option to restore system as before --up was called

### ISSUE THREAD

**Issue by nstinus** [wknapik/vpnfailsafe#16]
Your script is used in https://github.com/nstinus/nordvpn.

In our use case, people could want to use vpnfailsafe to ensure that an active service having a dropping connection is still safe but also having the option to stop the openvpn service in which case, they might want to come back to how it was before and still be able to connect to the internet. That means doing some things the documentation explicitly mentions as not being done (removal of firewall rules a.s.o.).
Is it reasonable? Is there a reason why it is not implemented?

**Comment by wknapik** [comment]
Hi @nstinus. I will publish a "reset" script this week.

**Comment by wknapik** [comment]
Hi @nstinus. I added the extras/ directory with some helpers, including vpnfailsafe_reset.sh, which does what you asked for.
The AUR package installs these files under /usr/share/doc/vpnfailsafe/ , without executable permissions.
I need to work on the AUR package anyway, so I'll look into whether this location, or permissions should be changed.

**Comment by nstinus** [comment]
@wknapik I confirm it works. Thank you!
Until you fix the package, I'll set up a workaround. Any issues with just setting x permissions on these scripts?

**Comment by wknapik** [comment]
Hi @nstinus. I don't think scripts should be run from /usr/share/doc. That's a place for documentation. At the same time I don't want to put them in /usr/bin, or /etc/openvpn/client, because most people probably don't want them there. They're meant as examples, that a few will choose to copy to some other location, maybe customize to their needs and use. As for vpnfailsafe_reset.sh specifically, I'm guessing the vast majority will be satisfied by `systemctl restart iptables.service`, or some such standard method of restoring iptables rules and won't care much about the /etc/hosts entries.

If your script wants to call vpnfailsafe_reset.sh for instance, it seems reasonable for that script to copy it so, say, /etc/openvpn/client and +x it. At the moment it seems to me like the best way to handle this.

I said I was planning to work on the Arch package, because OpenVPN 2.4 made /etc/openvpn/client a more suitable location for vpnfailsafe.sh, than /etc/openvpn, but I also don't want to break existing installations, where people already have /etc/openvpn/vpnfailsafe.sh hardcoded in their configs. I'll have to figure out a way to make this transition painless, when I have the spare time.

Thanks for the report.
