### ISSUE TITLE
POSIX instead of bash

### ISSUE THREAD

**Issue by jonascj** [wknapik/vpnfailsafe#17]
This is a feature request.
It would be awesome to port the script to not depend on bash, but be posix compliant.

**Comment by wknapik** [comment]
What would be the point in that ?

Bash is not the most expressive language to begin with. Dropping all its non-posix features would basically mean a complete rewrite in a worse language. That would require a lot of time and effort, would inevitably introduce new bugs and the end product would be less maintainable.

If this had any chance of running on, possibly very old, possibly non-Linux, systems, at least the portability argument would be valid, but vpnfailsafe is tied to Linux >=2.4, due to iptables. 

So given the massive disadvantages and no apparent upsides - why ?

Is it about not having to do `RUN apk add bash` in your Dockerfile ?;]

**Comment by jonascj** [comment]
Yeah, stupid request after reading your argument. Everyone can afford to keep bash besides their zsh/dash combos.

And yes, it was to not keep bash installed besides other shells, but that is stupid, likely I use many other bash dependent scripts without knowing it.

Please close this issue :-)

**Comment by wknapik** [comment]
No worries ;]
