### ISSUE TITLE
dns in resolv.conf different from the allowed route in iptables

### ISSUE THREAD

**Issue by ghost** [wknapik/vpnfailsafe#24]
Hi,
first thing first, thank you so much for the scripts and the time you spent on them, I really appreciate your work!

I have an issue that I am trying to debug without success and I would really appreciate your input on it.

When connecting to the VPN using the vpnfilesafe script I end up with a dns server in resolv.conf of XX.XX.16.1 and if I grep for XX.XX in iptables I end up with the following:

RETURN     all  --  XX.XX.48.0/22        0.0.0.0/0           
RETURN     all  --  0.0.0.0/0            XX.XX.48.0/22

I assume this is preventing the VPN connection from accessing the DNS server assigned by the VPN provider so I get no internet connection.

Sometimes restarting the connection fixes it but most of the times it doesn't. Ip route get 8.8.8.8 returns the following:

8.8.8.8 via XX.XX.48.1 dev tun0 src XX.XX.48.9 uid 1000

Thanks in advance and keep up the great work!

**Comment by wknapik** [comment]
Hi @bashruleseverythingaroundme. Thank you for the kind words ;]

As for your DNS issue - I'm afraid the information you gave me is not enough to figure it out, but I think I have a pretty good theory.

It seems that XX.XX.48.0/22 is the private network you're joining when you connect to the VPN and the server pushes XX.XX.16.1 as the DNS. The problem with this is that XX.XX.16.1 falls outside of the network carved out by the /22 netmask. This means, that the firewall rules meant to pass traffic to and from the private VPN network, will not pass traffic to and from the DNS server, making the DNS server unreachable (well, actually, only the responses would be blocked, but that's beside the point).

If my theory is correct, this is misconfiguration on your VPN provider's part. In that case, you could contact them and explain, that they shouldn't push DNS servers available on a private network the user isn't on.

What's weird though, is that reconnecting can fix the issue. It could be, that different DNS servers are pushed on reconnection, that's entirely possible, but doesn't seem very likely.

To properly look into this, I would need the output of the following commands:
- `ip route`
- `iptables -S`
- `resolvconf -l`
- `cat /etc/resolv.conf`

If you'd rather not post this information here, feel free to send it over email (encrypted, if you like), or some other way. My email is wmknapik at gmail com and the PGP key signature is in my profile description.

**Comment by ghost** [comment]
Hi @wknapik,

I've sent you an email with the output of the commands above, I've also discovered this on the vpn provider website:

"Our DNS servers are not publicly accessible from the Internet, they are only accessible once connected to IVPN. To work out the address of the closest DNS server simply look at the IP assigned to you when you connect. The DNS servers are in the format 10.x.x.1. For example, if you receive the address 10.16.4.66 then the DNS is on 10.16.4.1."

So by the look of it, the DNS should be on the same network?

Thanks again

**Comment by wknapik** [comment]
> Hi @wknapik,

Hi @bashruleseverythingaroundme. Sorry for the late response - 'tis the season to be busy...

> I've sent you an email with the output of the commands above, I've also discovered this on the vpn provider website:

Yep, I got your email and it seems to confirm my suspicion.

The problem is that vpnfailsafe creates a firewall rule specifically to pass traffic from the internal VPN IP range, but that range excludes the IP of the DNS server, so the responses from the DNS server end up being DROPped.

You can confirm that yourself, using an online subnet calculator. Here's a random result from google - https://mxtoolbox.com/subnetcalculator.aspx. If you enter the XX.XX.48.0 IP you mentioned and the /22 netmask, it will show you the range of IPs that network includes. You will notice, that it doesn't include the XX.XX.16.1 IP address of the DNS server.

> "Our DNS servers are not publicly accessible from the Internet, they are only accessible once connected to IVPN. To work out the address of the closest DNS server simply look at the IP assigned to you when you connect. The DNS servers are in the format 10.x.x.1. For example, if you receive the address 10.16.4.66 then the DNS is on 10.16.4.1."

That's demonstrably false. You can take a look at the info you sent me over email - the DNS server you got assigned does not follow the rule they describe.

I'd be happy to comment on the issue you opened with the VPN provider, if that's possible (feel free to add me to CC, if this is being handled over email).

> So by the look of it, the DNS should be on the same network?

Unfortunately not.

There is no generic solution to this problem, because vpnfailsafe can only rely on the configuration pushed by the VPN server. You could manually add a firewall rule to explicitly pass traffic from the DNS server. Something along the lines of `iptables -I VPNFAILSAFE_INPUT -s <DNS_IP> -p udp --sport 53 -i tun0 -j ACCEPT`, but that's probably not something you want to be doing every time you (re)connect.

I'm working on something that would be an answer to this problem, but I don't think I'll be publishing it  soon ;/ I'm afraid the only good solution is for your VPN provider to fix the issue on their end.

**Comment by ghost** [comment]
Hi @wknapik,

thank you so much for the reply and the in depth explanation :) definitely the season to be busy... 

I've just opened a ticket on the IVPN website (unfortunately there was no option to CC) and I've pointed the ticket to this thread hoping they are going to address the issue. As it stands right now they advised me to use an external DNS stating that this is the expected behaviour. I've highlighted their documentation where they state the IP should be on the same range and I'll update the ticket if they sort it out.

Assuming I am going to use an external DNS while they either fix the issue or I find a different VPN provider is it enough to manually update my resolv.conf and then write protect it (chattr +i) to always use OpenDNS or GoogleDNS or do I also need to add some rules to iptables to prevent a leak? I am assuming all the traffic to the manually forced DNS will go through the TUN anyway, am I correct in assuming so?

Also is there a VPN provider you would suggest?

Last but not least, thanks again for all your help, I really appreciate it! 
Wish you a wonderful Christmas and an amazing 2018!

**Comment by wknapik** [comment]
> Assuming I am going to use an external DNS while they either fix the issue or I find a different VPN provider is it enough to manually update my resolv.conf and then write protect it (chattr +i) to always use OpenDNS or GoogleDNS or do I also need to add some rules to iptables to prevent a leak? I am assuming all the traffic to the manually forced DNS will go through the TUN anyway, am I correct in assuming so?

If you use a DNS with a public IP, the traffic will go over the tunnel, so everything should just work.

The `chattr +i` is a pretty heavy-handed hack, but it should work. Just don't forget about it ;]

The nice thing about using your VPN provider's DNS server in this case is that your queries never pass through the open internet, so noone can listen in (except your VPN provider, of course), but the solution you described has the benefit of being simple.

> Also is there a VPN provider you would suggest?

I usually cycle between providers from this list https://torrentfreak.com/vpn-services-anonymous-review-2017-170304/ every month (excluding the ones in [Five Eyes](https://en.wikipedia.org/wiki/Five_Eyes) jurisdictions), trying to find edge cases in vpnfailsafe and just checking out what interesting technical choices some of them make.

I should've kept notes about them, but I never did, so I mostly forgot which ones I liked and which I didn't. I do remember, that ExpressVPN has the same DNS issue you're having and I remember Private Internet Access annoying me both as the vpnfailsafe developer (returning different IPs for every DNS query) and user (sending passwords in plain text over email ? are you serious ?). I recently noticed BolehVPN has a zcash payment option, which is great. I don't really know more about any of them, beyond what you can read in the torrentfreak article and on their official sites, in reviews, etc., so use your own judgement. If I were to recommend one, it would probably be Mullvad. I wish I knew I could trust Cryptostorm, because they have some interesting stuff going on...

> Last but not least, thanks again for all your help, I really appreciate it!

No problem ;]

> Wish you a wonderful Christmas and an amazing 2018!

Thanks, you too!;]

**Comment by ghost** [comment]
Hi @wknapik,

just a quick update on this, someone at IVPN is taking care of the issue and they will roll out a fix in the following weeks!

Thanks again for all you help and enjoy the holidays! ;)

**Comment by wknapik** [comment]
That's great! I'll keep this issue open until we confirm that everything is working with IVPN (or your subscription runs out, but then someone from IVPN could run a test for us).

Thanks for the holiday wishes - it was nice, while it lasted ;]

**Comment by ghost** [comment]
Hi @wknapik,

someone from IVPN just got in touch, they have released a fix and now everything is working as expected! ;)

Have a super 2018 and thank again for all your help!

I'm closing the ticket down!

**Comment by wknapik** [comment]
> someone from IVPN just got in touch, they have released a fix and now everything is working as expected! ;)

Awesome :]

> Have a super 2018 

You too :)

> and thank again for all your help!

Thanks for the report :)

**Comment by ncoder-1** [comment]
Hi,
I know the issue is closed, but I happen to have this exact issue with Witopia.  They also use a non-public internal DNS which is pushed by their server.conf and unless I do `iptables -I VPNFAILSAFE_INPUT -s <DNS_IP> -p udp --sport 53 -i tun0 -j ACCEPT` like you suggested, it will block my dns requests.

Is there a way to configure this from within the script (like a variable you turn `true` or something) to not have to run the command after each VPN connection?

**Comment by wknapik** [comment]
Hi @elimpnick. Sorry for the delay in my response, I've been away for a long time, but I'm back now. There is an open issue for this - #26. I will implement a proper fix for this. Can't promise a deadline, but I will look at it this weekend. Thanks for the report - let's continue in #26 from now on.
