### ISSUE TITLE
NetworkManager

### ISSUE THREAD

**Issue by veloute** [wknapik/vpnfailsafe#29]
Does this script work with the OpenVPN plugin for NetworkManager?

**Comment by wknapik** [comment]
Hi @veloute. Sorry it took me so long to respond, I've been away for a few weeks.

This script works with OpenVPN. If NetworkManager allows you to pass `--up /path/to/vpnfailsafe.sh --down /path/to/vpnfailsafe.sh`, then that would work, because OpenVPN would invoke the script, with all the environment variables set, that vpnfailsafe expects. However, if NetworkManager has it's own notion of an up/down script, where it's executed by NetworkManager itself, then it most likely won't work.

It's a matter of what calls the script (or rather, whether whatever calls the script sets the same environment variables, that OpenVPN would), so you may choose to set up your network connection using NetworkManager, but create the VPN tunnel on top of it with something else (like start it from your init scripts for instance, or just call openvpn directly) and that would certainly work.

So the short answer is "probably no (*)", but I'll confirm this when I have a moment, probably this weekend.

**Comment by wknapik** [comment]
Yep, NetworkManager does not support passing --up/--down to OpenVPN, so if you want to use vpnfailsafe, OpenVPN will have to be started by something else, like your init scripts (see: https://github.com/wknapik/vpnfailsafe/issues/11#issuecomment-312518942 for a previous answer to the same question).

I don't see any [open issues](https://bugzilla.gnome.org/buglist.cgi?quicksearch=product%3A%22NetworkManager%22%20vpn) for this limitation. I'd recommend filing a bug report/feature request at the gnome bug tracker, but I see these guys are [not making it easy](https://bugzilla.gnome.org/enter_bug.cgi)...
